### ISSUE TITLE
Cerberi Demons have "unlimited ammo"

### ISSUE THREAD

**Issue by Malifious** [BlackDragonN001/FERemastered#110] opened 2020-05-24 00:29 UTC
Demons will continually drop drones (at least the CPU's does) until destroyed rather than acting like an APC or the old Demon and running out of drones after the first I think 8.

**Comment by bornlibra23** [comment] 2020-05-24 08:33
Thats okay. It can be viewed as a small nexus.

**Comment by jack775544** [comment] 2020-05-24 10:30
The Demon has always worked like this. It uses regular (regenerating) ammo for dropping drones and after enough time it will have regained enough ammo to spawn a new pair of drones.

So closing this as it is working as intended.

**Closed by jack775544** 2020-05-24 10:30 UTC
