### ISSUE TITLE
Mission 5 - Firing Back: Recycler doesnt go to the final nav point

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#30] opened 2020-04-01 17:13 UTC
The recycler turns to blue highlight & cant be controlled. It doesnt move automatically to the final nav beacon & if forced there by the game editor tryes to go back to the original position over the mountains & cliffs.

**Comment by GraveyBoi** [comment] 2020-04-01 17:59
You have to be near it for it to start the pathing. This has worked prior, but I can test this again.

**Comment by bornlibra23** [comment] 2020-04-01 18:02
I thought so too. So I went near it but nothing happened. Then I destroyed
all the buildings around it because it was boxed in but nothing happened. I
went near it each time but nothing.

**Comment by GraveyBoi** [comment] 2020-04-02 16:40
I had no problem with this, did a full playthrough without entering the editor and it ran fine.

**Comment by GraveyBoi** [comment] 2020-04-02 16:41
might need to try to isolate what caused it to fail to path, but it is working

**Comment by JJ173** [comment] 2020-04-07 16:14
Any update on replicating this? If nobody can replicate it, I'll close the issue. Since there are no steps, and Gravey has done it twice, I think this could be fine.

**Comment by bornlibra23** [comment] 2020-04-09 06:03
I will play it again & try to make it reproducible.

**Comment by Feared1** [comment] 2020-04-21 20:46
The terrain at the beginning is not suited well for a recycler; mine fell into the water several times, and it will not make it with a direct go-to; this is not acceptable (it also tried to climb up the hill to head straight to the nav from spawn, then fell back into the water). Rework the terrain so there's no danger of falling into the water, and fix Recycler's physics to not be so slippery.

**Comment by JJ173** [comment] 2022-09-10 17:11
Closed - confirmed pathing is fine. I have had no issues at the start of the mission when the Recycler deploys, and I've also tested it going to Nav Delta. You have to collect the Recycler first (be within 50 meters).

**Closed by JJ173** 2022-09-10 17:11 UTC
Labels: Firing Back (SP)
