### ISSUE TITLE
Hammer Texture Issue, Mission 6 - Sheep's Clothing

### ISSUE THREAD

**Issue by Malifious** [BlackDragonN001/FERemastered#104] opened 2020-05-22 22:58 UTC
The two hammers that spawn in kind of have the right texture, but are grayscaled out it looks like. Something went wrong. I haven't seen any issues with Hammer texturing before.

**Comment by jack775544** [comment] 2020-05-24 11:02
I see this issue with Hammers on every map. The issue is that the old placeholder model for the hammer is not using a normal map (BZ2 didn't need them but BZCC does) for it's texturing. This will be fixed once the remastered hammer is done so I will close this one.

**Closed by jack775544** 2020-05-24 11:02 UTC
